### ISSUE TITLE
Possibly flawed implementation of image blending

### ISSUE THREAD

**Issue by vbocan** [silvia-odwyer/photon#132]
I am trying to reproduce the "multiply" and "screen" blend modes as described [on the Wikipedia Blend Modes page](https://en.wikipedia.org/wiki/Blend_modes#Multiply).

These are the original images mentioned in the Wikipedia article:

Bottom layer:
![180px-Blend_modes_2 -bottom-layer](https://user-images.githubusercontent.com/7954952/180634203-24365f85-132e-49bd-91e9-db40b71e3b20.jpg)

Top layer:
![180px-Blend_modes_1 -top-layer](https://user-images.githubusercontent.com/7954952/180634214-fe94b429-55c9-43eb-87a6-9e8ba6ed26c8.jpg)

Here we can see the difference, reference vs. photon rendering:

**Multiply Blend Mode**
Reference result from the Wikipedia article:
![180px-Blend_modes_4 -multiply](https://user-images.githubusercontent.com/7954952/180634244-b6c6b80b-0363-4498-afe5-ff7dc68ba50c.jpg)
Image produced using the photon crate:
![photon-blend-multiply](https://user-images.githubusercontent.com/7954952/180634266-42d4a6b9-edab-4461-921b-95c33a0ac796.jpg)

**Screen Blend Mode**
Refence result from the Wikipedia article:
![180px-Blend_modes_5 -screen](https://user-images.githubusercontent.com/7954952/180634283-0f02f17e-604f-43af-b2ef-179553829be3.jpg)
Image produced using the photon crate:
![photon-blend-screen](https://user-images.githubusercontent.com/7954952/180634295-66574c6b-ed12-445c-93b2-88a1e9141532.jpg)

There is a significant difference between the expected images and the results given by the photon crate. Is blending implementation flawed?

**Comment by vbocan** [comment]
Just for the record, here's the Rust code I used to generate the resulting images:

```
use photon_rs::multiple::blend;
use photon_rs::native::open_image;
use photon_rs::native::save_image;

fn main() {
    // https://en.wikipedia.org/wiki/Blend_modes#Multiply
    let mut img = open_image("180px-Blend_modes_2.-bottom-layer.jpg").expect("File should open");
    let img2 = open_image("180px-Blend_modes_1.-top-layer.jpg").expect("File should open");
    blend(&mut img, &img2, "screen"); // Also try with "multiply"
    save_image(img, "photon-blend-screen.jpg");
}
```

**Comment by silvia-odwyer** [comment]
@vbocan Hi Valer, thanks very much for opening this issue and letting me know about this! 👍 I'll be sure to take a look into what's causing the bug, and will keep you updated ✅ 😄

**Comment by silvia-odwyer** [comment]
@vbocan I've just fixed the bug, it was due to a mismatch in the color space being used when blending the images together. This mismatch resulted in the differing outputs shown in the images above. If you update the library and re-run the code, you should get the results as shown in the Wikipedia images now.

Thanks again for letting me know about this, it's greatly appreciated! 😄 If you have any other questions, don't hesitate to let me know 👍

**Comment by vbocan** [comment]
Thank you for fixing the issue, you've just saved my project that uses photon-rs.

I just ran `cargo update` on my project but I'm still seeing photon-rs version 0.3.1, so I guess it takes a bit of time for the new version to propagate to crates.io.

**Comment by silvia-odwyer** [comment]
@vbocan Glad to help! 😄 It hasn't been published on crates.io yet, but in the `Cargo.toml`, you can set the photon-rs dependency like so:

```
photon-rs = { git = "https://github.com/silvia-odwyer/photon" }
```
Hope that helps! The new version will be published on crates.io in the near future also ✅

**Comment by vbocan** [comment]
Works like a charm!!!
